Remove separate treatment queries
plazi/synolib pull request #9
Opened 2024-03-22 19:17 UTC by nleanba

See https://github.com/factsmission/synospecies/issues/128

2024-03-25 14:24 UTC, retog commented
![image](https://github.com/plazi/synolib/assets/110756/1aa7abb6-a885-413c-b506-be62067ae8a6)
On the left on this PR, on main. Why are no more treatments shown?

2024-03-25 14:47 UTC, nleanba commented
> On the left on this PR, on main. Why are no more treatments shown?

This was because the script in `index.html` was not updated and ran into errors. I have fixed it now

2024-03-25 17:01 UTC, retog requested changes, later dismissed
Revert back to throwing exceptions, except there's a good reason.

Otherwise it looks good!

2024-03-25 17:01 UTC, retog commented on SynonymGroup.ts
> +          return new Promise<SparqlJson>((_, reject) => reject(error));
Why this change, isn't the result exactly the same? If not, could it be simplified to: `return Promise.reject(error);`?

2024-03-25 17:01 UTC, retog commented on SynonymGroup.ts
For consistency within this file, I suggest to use async functions and never the Promise-constructor.

2024-03-26 09:14 UTC, nleanba commented on SynonymGroup.ts
> +          return new Promise<SparqlJson>((_, reject) => reject(error));
You are correct, the result is the same. I don't know why I changed this

2024-03-26 09:34 UTC, nleanba commented on SynonymGroup.ts
I have now removed all `new Promise(...)` constructs that resolve instantly, and replaced most of them with `Promise.resolve(...)`.

I deem it unnecessary to convert all function which return promises to async functions, I suggest leaving all instances of `return sparqlEndpoint.getSparqlResultSet(...).then(..., catch);` as-is.

2024-03-26 13:34 UTC, merged